name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - "policies/**"
      - "website/**"
      - ".github/workflows/deploy-website.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git operations

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        working-directory: ./website
        run: npm ci

      - name: Generate policy data
        working-directory: ./website
        run: npm run generate-data

      - name: Build Next.js site
        working-directory: ./website
        run: npm run build
        env:
          NEXT_PUBLIC_USE_BASE_PATH: "true" # GitHub Pages needs /MAMIP basePath

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
